import browser_cookie3
import tempfile
import os

def export_cookies():
    try:
        # Try Chrome first
        cookies = browser_cookie3.chrome(domain_name='.youtube.com')
        cookies_file = os.path.join(tempfile.gettempdir(), 'youtube_cookies.txt')
        
        with open(cookies_file, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# https://curl.haxx.se/rfc/cookie_spec.html\n")
            f.write("# This file was generated by browser_cookie3\n\n")
            
            for cookie in cookies:
                if '.youtube.com' in cookie.domain:
                    secure = "TRUE" if cookie.secure else "FALSE"
                    http_only = "TRUE" if cookie.has_nonstandard_attr('HttpOnly') else "FALSE"
                    # Use a far future expiration date
                    expires = "1735689600"  # 2025-01-01
                    
                    f.write(f"{cookie.domain}\tTRUE\t{cookie.path}\t{secure}\t{expires}\t{cookie.name}\t{cookie.value}\n")
        
        print(f"Cookies saved to: {cookies_file}")
        return cookies_file
    except Exception as e:
        if "Could not copy Chrome cookie database" in str(e):
            print("Error: Could not access Chrome cookies. Please close all Chrome browser windows and try again.")
        else:
            print(f"Error with Chrome: {e}")
        try:
            # Try Edge if Chrome fails
            cookies = browser_cookie3.edge(domain_name='.youtube.com')
            cookies_file = os.path.join(tempfile.gettempdir(), 'youtube_cookies.txt')
            
            with open(cookies_file, 'w', encoding='utf-8') as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# https://curl.haxx.se/rfc/cookie_spec.html\n")
                f.write("# This file was generated by browser_cookie3\n\n")
                
                for cookie in cookies:
                    if '.youtube.com' in cookie.domain:
                        secure = "TRUE" if cookie.secure else "FALSE"
                        http_only = "TRUE" if cookie.has_nonstandard_attr('HttpOnly') else "FALSE"
                        # Use a far future expiration date
                        expires = "1735689600"  # 2025-01-01
                        
                        f.write(f"{cookie.domain}\tTRUE\t{cookie.path}\t{secure}\t{expires}\t{cookie.name}\t{cookie.value}\n")
            
            print(f"Cookies saved to: {cookies_file}")
            return cookies_file
        except Exception as e:
            if "Could not copy Edge cookie database" in str(e):
                print("Error: Could not access Edge cookies. Please close all Microsoft Edge browser windows and try again.")
            else:
                print(f"Error with Edge: {e}")
            return None

if __name__ == '__main__':
    export_cookies()
