/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120061-gcfd1f81e7d-20250630"
#endif /* AVUTIL_FFVERSION_H */
